title: Valour HK Ltd
email: info@valourhk.com
description: A class above the rest
baseurl: ''
url: url
meta_author: Tom Hamilton Stubber

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
address: Golden Sun Centre, 59-67 Bonham Strand West, Sheung Wan, Hong Kong
phone:
social:
  - title: twitter
    url:
  - title: facebook
    url: https://www.facebook.com/valourhkltd
  - title: instagram
    url:
  - title: linkedin
    url:
  - title: google
    url:
  - title: pinterest
    url:
  - title: youtube
    url:
office_hours:
  - "Mon - Fri: 9am - 5pm"
  - "Weekends: Open"
socket_key: '9c79f14df986a1ec693c'
tutorcruncher_url: https://secure.tutorcruncher.com/valour
ga_analytics_key: UA-151120913-1
